# Site settings
title: AACINI
description: AACINI - Asociación Argentina de Carreras de Ingeniería Industrial
baseurl: ""
url: "http://aacini.com.ar"
address: "San José 964, PB. A, Capital Federal, Argentina"
phone: "Tel/Fax: (011) 4304-7997/9960"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
prose:
  siteurl: "http://aacini.com.ar"
  ignore: ['_includes','_layouts','_sass','css','img','.gitignore','_config.yml','README.md']

environment: development
